import json

from .config import (
        BLUESHIFT_PRODUCT, BLUESHIFT_PLATFORM, BLUESHIFT_DIR, BLUESHIFT_DISPLAY_VERSION,
        BLUESHIFT_CONFIG, BLUESHIFT_API_KEY_ID, BLUESHIFT_SECRET_ACCESS_KEY,
        BLUESHIFT_COMMAND_ACCESS, BLUESHIFT_HEALTHCHECK, BLUESHIFT_LIVE_BROKER_NAME,
        BLUESHIFT_BACKTEST_BROKER_NAME, BLUESHIFT_STREAMING_DATA, 
        BLUESHIFT_PRIMING_RUN, BLUESHIFT_SECURE_CODE, BLUESHIFT_DISABLE_IPV6, 
        BLUESHIFT_EAGER_SCHEDULING, BLUESHIFT_DEBUG_MODE, SESSION_ID, 
        BLUESHIFT_BROKER_SERVICE, BLUESHIFT_BACKTEST_INIT_SCRIPT, STREAMING_TIMEOUT,
        BLUESHIFT_LIVE_INIT_SCRIPT, BLUESHIFT_DISABLE_KILL_SWITCH, 
        ELAPSED_TIME_THRESHOLD, ALLOW_USER_IMPORT, MULTI_TENANCY, LOCK_TIMEOUT,
        MARKET_ORDER_TIMEOUT, OPEN_ORDER_TIMEOUT, BLOTTER_UPDATE_TIMEOUT, 
        USE_IOC_SQUAREOFF, USE_IOC_EXIT_SQUAREOFF, DEFAULT_IOC_ORDER, 
        DEFAULT_COOLOFF, DEFAULT_CAPITAL, IOC_WAIT_TIME, ORDER_CHECK_TIMEOUT, 
        ORDER_RETRY_TIME, MAX_ITER_IOC_EXIT, USE_MULTI_SQUAREOFF, RAISE_CAPITAL_ERROR, 
        ALLOW_EXTERNAL_EVENT, SEND_POSITION_DATA, SEND_TRADE_DATA, 
        BLOTTER_MISSING_ORDER_THRESHOLD, EXIT_ORDER_TIMEOUT, RMS_LIMIT_THRESHOLD, 
        BLUESHIFT_CALENDAR_START, register_config, get_config, _default_config)

from .defaults import (
        BLUESHIFT_PATH, SITE_PACKAGE_PATH, get_product_name, 
        blueshift_root, blueshift_dir, blueshift_data_path, blueshift_temp_dir,
        blueshift_source_path, blueshift_run_path, blueshift_log_path, blueshift_cache_dir,
        blueshift_saved_objs_path, blueshift_saved_orders_path,
        blueshift_saved_transactions_path, blueshift_saved_positions_path,
        blueshift_saved_performance_path, blueshift_reset_run_path,
        get_config_alerts, get_config_recovery, get_config_channel,
        get_blueshift_server, get_config_resource, get_config_broker_details,
        get_config_env_vars, get_config_oneclick, get_config_smart_orders)

def generate_default_config(filename=None) -> str|None:
    if not filename:
        return json.dumps(_default_config)

    with open(filename, "w") as fp:
        json.dump(_default_config, fp)

__all__ = ['BLUESHIFT_PRODUCT', 
           'BLUESHIFT_PLATFORM', 
           'BLUESHIFT_DISPLAY_VERSION',
           'BLUESHIFT_DIR',
           'BLUESHIFT_CONFIG', 
           'BLUESHIFT_SECURE_CODE',
           'BLUESHIFT_DISABLE_IPV6',
           'BLUESHIFT_API_KEY_ID', 
           'BLUESHIFT_SECRET_ACCESS_KEY',
           'BLUESHIFT_COMMAND_ACCESS', 
           'BLUESHIFT_HEALTHCHECK', 
           'BLUESHIFT_PRIMING_RUN',
           'BLUESHIFT_LIVE_BROKER_NAME',
           'BLUESHIFT_BACKTEST_BROKER_NAME',
           'BLUESHIFT_STREAMING_DATA',
           'BLUESHIFT_EAGER_SCHEDULING',
           'BLUESHIFT_DEBUG_MODE',
           'SESSION_ID',
           'BLUESHIFT_BROKER_SERVICE',
           'BLUESHIFT_PATH', 
           'SITE_PACKAGE_PATH',
           'BLUESHIFT_BACKTEST_INIT_SCRIPT',
           'BLUESHIFT_LIVE_INIT_SCRIPT',
           'BLUESHIFT_DISABLE_KILL_SWITCH',
           'ELAPSED_TIME_THRESHOLD',
           'ALLOW_USER_IMPORT',
           'ALLOW_EXTERNAL_EVENT',
           'SEND_POSITION_DATA',
           'SEND_TRADE_DATA',
           'RAISE_CAPITAL_ERROR',
           'MULTI_TENANCY',
           'LOCK_TIMEOUT',
           'STREAMING_TIMEOUT',
           'MARKET_ORDER_TIMEOUT',
           'OPEN_ORDER_TIMEOUT',
           'BLOTTER_UPDATE_TIMEOUT',
           'BLOTTER_MISSING_ORDER_THRESHOLD',
           'USE_IOC_SQUAREOFF',
           'USE_IOC_EXIT_SQUAREOFF',
           'DEFAULT_IOC_ORDER',
           'DEFAULT_COOLOFF',
           'DEFAULT_CAPITAL',
           'IOC_WAIT_TIME',
           'EXIT_ORDER_TIMEOUT',
           'ORDER_RETRY_TIME',
           'ORDER_CHECK_TIMEOUT',
           'MAX_ITER_IOC_EXIT',
           'USE_MULTI_SQUAREOFF',
           'RMS_LIMIT_THRESHOLD',
           'BLUESHIFT_CALENDAR_START',
           'register_config', 
           'get_config',
           'generate_default_config',
           'get_product_name',
           'blueshift_root', 
           'blueshift_dir', 
           'blueshift_temp_dir',
           'blueshift_cache_dir',
           'blueshift_data_path',
           'blueshift_source_path', 
           'blueshift_run_path', 
           'blueshift_log_path',
           'blueshift_saved_objs_path', 
           'blueshift_saved_orders_path',
           'blueshift_saved_transactions_path', 
           'blueshift_saved_positions_path',
           'blueshift_saved_performance_path', 
           'blueshift_reset_run_path',
           'get_config_alerts', 
           'get_config_recovery', 
           'get_config_channel',
           'get_blueshift_server', 
           'get_config_resource', 
           'get_config_broker_details',
           'get_config_env_vars', 
           'get_config_oneclick', 
           'get_config_smart_orders',
           ]


