
from blueshift.lib.common.enums import AlgoState as STATE, AlgoMode, ExecutionMode

class _AlgoStateMachine:
    name:str
    mode:AlgoMode
    execution_mode:ExecutionMode
    state:str

    def __init__(self, name:str, mode:AlgoMode, execution_mode:ExecutionMode):...
    def is_running(self) -> bool:...
    def is_paused(self) -> bool:...
    def set_pause(self):...
    def reset_pause(self):...
    def reset_state(self):...
    def is_STOPPED(self) -> bool: ...
    def is_TRADING_BAR(self) -> bool: ...
    def fsm_initialize(self):...
    def fsm_before_trading_start(self):...
    def fsm_handle_data(self):...
    def fsm_after_trading_hours(self):...
    def fsm_analyze(self):...
    def fsm_heartbeat(self):...
    def fsm_stop(self):...