from blueshift.lib.exceptions import (
        UserDefinedException, ExceptionHandling, ValidationError,
        BlueshiftException, NoSuchPipeline, ServerError, BadDataError,
        IllegalRequest, BrokerError, APIError, BrokerConnectionError,
        TradingBlockError, HistoryWindowStartsBeforeData,
        NoDataForAsset, TradingControlError, SymbolNotFound,
        InsufficientFund, OrderAlreadyProcessed, AlgoOrderError,
        PositionNotFound, OrderNotFound, PreTradeCheckError, SquareoffError,
        DataAPIError)

from blueshift.lib.exceptions import (
        BlueshiftLibraryException, TimeSeriesException, 
        TechnicalsException, StatsException, OHLCVException,
        ResampleError, RollingWindowError, ExpandingWindowError,
        ModelError, OrderError, OrderNotReady, PriceOutOfRange, 
        AlgoStateError)

__all__ = [
           'UserDefinedException',
           'ExceptionHandling',
           'ValidationError',
           'BlueshiftException', 
           'NoSuchPipeline', 
           'ServerError', 
           'BadDataError',
           'IllegalRequest', 
           'BrokerError', 
           'APIError', 
           'BrokerConnectionError',
           'TradingBlockError', 
           'HistoryWindowStartsBeforeData',
           'NoDataForAsset', 
           'TradingControlError', 
           'SymbolNotFound',
           'InsufficientFund',
           'OrderAlreadyProcessed',
           'OrderNotReady',
           'OrderError',
           'PriceOutOfRange',
           'BlueshiftLibraryException', 
           'TimeSeriesException', 
           'TechnicalsException', 
           'StatsException', 
           'OHLCVException',
           'ResampleError', 
           'RollingWindowError', 
           'ExpandingWindowError',
           'ModelError', 
           'AlgoOrderError',
           'PositionNotFound',
           'OrderNotFound',
           'PreTradeCheckError',
           'SquareoffError',
           'DataAPIError',
           'AlgoStateError',
           ]

try:
    from .lib.exceptions import (
                NoFurtherDataError,
                WindowLengthNotPositive,
                UnsupportedDataType,
                NonExistentAssetInTimeFrame,
                UnsupportedPipelineOutput,
                DTypeNotSpecified,
                InvalidOutputName,
                NonSliceableTerm,
                NonWindowSafeInput,
                NotDType,
                NonPipelineInputs,
                TermInputsNotSpecified,
                TermOutputsEmpty,
                UnsupportedDType,
                WindowLengthNotSpecified,
                BadPercentileBounds,
                UnknownRankMethod,
                IncompatibleTerms,
                )
except ImportError:
    pass
else:
    __all__.extend([
            'NoFurtherDataError',
            'WindowLengthNotPositive',
            'UnsupportedDataType',
            'NonExistentAssetInTimeFrame',
            'UnsupportedPipelineOutput',
            'DTypeNotSpecified',
            'InvalidOutputName',
            'NonSliceableTerm',
            'NonWindowSafeInput',
            'NotDType',
            'NonPipelineInputs',
            'TermInputsNotSpecified',
            'TermOutputsEmpty',
            'UnsupportedDType',
            'WindowLengthNotSpecified',
            'BadPercentileBounds',
            'UnknownRankMethod',
            'IncompatibleTerms',
            ])