from __future__ import annotations
from typing import TYPE_CHECKING, Callable
from enum import Enum

from blueshift.interfaces.trading.exit_handler import IExitHandler

if TYPE_CHECKING:
    import numpy as np
    from blueshift.lib.common.sentinels import noop
    from blueshift.interfaces.trading._exit_handler import ExitMethod
    from blueshift.interfaces.context import IContext
    from blueshift.interfaces.assets._assets import Asset
    from blueshift.core.algorithm.algorithm import TradingAlgorithm


class ExitHandler(IExitHandler):
    """
        A handler that implements stoploss and take profit. It also 
        tracks square-off exits and enforces order cool-off period 
        following any exit orders (stoploss, takeprofit or user trigger
        square-offs).
    """
    def __init__(self, algo:TradingAlgorithm, cooloff_period:float=30):...
    def set_cooloff_period(self, value:float):...
    def get_cooloff_period(self) -> float:...
    def reset(self, roll:bool=True):...
    def reset_stoploss(self, context:IContext, asset:Asset|None):...
    def reset_takeprofit(self, context:IContext, asset:Asset|None):...
    def add_stoploss(self, context:IContext, asset:Asset|None, method:ExitMethod, target:float, 
                       callback:Callable=noop, trailing:float=0, do_exit:bool=True, 
                       entry_level:float=np.nan, rolling:bool=False):...
    def add_takeprofit(self, context:IContext, asset:Asset|None, method:ExitMethod, target:float, 
                       callback:Callable=noop, do_exit:bool=True, entry_level:float=np.nan, 
                       rolling:bool=False):...
    def get_stoploss(self, context:IContext, asset:Asset|None):...
    def get_takeprofit(self, context:IContext, asset:Asset|None):...
    def copy_stoploss(self, source:Asset|None, target:Asset|None):...
    def copy_takeprofit(self, source:Asset|None, target:Asset|None):...
    def set_cooloff(self, assets:Asset|list[Asset]|None=None, squareoff:bool=False, 
                    is_global:bool=False):...                
    def reset_cooloff(self, context:IContext, asset:Asset|None):...
    def validate_cooloff(self, asset:Asset|None=None):...
    def validate_squareoff(self, asset:Asset|None=None):...
    def remove_context(self, ctx:IContext):...
    def check_exits(self, reset:bool=False):...
    def is_empty(self, context:IContext|None=None) -> bool:...
    
